### ISSUE TITLE
Publish implied alignment algorithm application on phylogenetic networks

### ISSUE THREAD

**Issue by recursion-ninja** [amnh/PCG#37] opened 2017-04-20 23:04 UTC
We should define the straight forward way to derive the implied alignment(s) on a phylogenetic network. This should take into account the optimal "rooting" of the dynamic character in the phylogenetic network. Lastly should perform a comparison in terms of time and scoring between alignment generated from an implied alignment in a phylogenetic network and those alignments generated from more classical sequence alignment software.

We can look to Ford & Wheeler's paper for structure and a starting point for the comparisons.

**Comment by ima-hima** [comment] 2018-03-02 16:54
Closed as dupe of #31.

**Closed by ima-hima** 2018-03-02 16:54 UTC
Labels: publication

**Comment by recursion-ninja** [comment] 2020-11-17 17:06
Just a little extra commentary on the duplicate status:

The binary tree algorithm for implied alignment will be interpolated in the phylogenetic network context the the exact same way as all other binary tree algorithms. It is captured by the general case which will be explained in #32.
